/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ktransformer.customized.sdk.java;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
